### ISSUE TITLE
mojoQuery bug

### ISSUE THREAD

**Issue by devin87** [scottcgi/MojoJS#1]
1. html: &lt;a id="a" /&gt;
   selector: 
       a#a   =>  mojoQuery: 0 results
       #a.b  =>  mojoQuery: 1 results
2. html:&lt;a class="a b c"&gt;
   selector: 
       .a.b   =>  mojoQuery: 0 results
3. html:&lt;a class="a b"&gt;
   selector: 
       .ab   =>  mojoQuery: 1 results

**Comment by scottcgi** [comment]
I see, next release will fixed
